Fontawesome verlinken----------------------

Fontawesome download-> extract -> webfonts folder -> copy this 3 files (fa-brands.400.woff2, fa-regular.400.woff2 and fa-solid.400.woff2) then
create folder in project folder stucture name it webfonts and paste this 3 files in it
then go in extrated fonteawesome folder and copy all.min.css into  styles project folder and then link it in html


Google fonts---------------------------